const INITIAL_BOARD_WIDTH = 58;
const INITIAL_BOARD_HEIGHT = 32;
const INITIAL_MIN_BOARD_WIDTH = 10;
const INITIAL_MIN_BOARD_HEIGHT = 10;
const INITIAL_MAX_BOARD_WIDTH = 100;
const INITIAL_MAX_BOARD_HEIGHT = 80;
const INITIAL_TICK_DELAY = 20;

export default {
	INITIAL_BOARD_WIDTH,
	INITIAL_BOARD_HEIGHT,
	INITIAL_MIN_BOARD_WIDTH,
	INITIAL_MIN_BOARD_HEIGHT,
	INITIAL_MAX_BOARD_WIDTH,
	INITIAL_MAX_BOARD_HEIGHT,
	INITIAL_TICK_DELAY
};
